---
#roles/user/tasks/main.yml

#add group
- group: name={{ work_user }} state=present
- group: name=sudo state=present

#add user
#密码默认123456
- user: name={{ work_user }} comment={{ work_user }} uid=1040 group={{ work_user }} update_password=always password=$6$Ck7YuxCy3YwP6xK$QjsDn4qtYzV32ast95nWG2IrwRKxcbk/THqyfABZSETBVsucL3fH9hZ7rS7nSTbw3a.gvVuBZWSKQMWDJB/Uk0 shell=/bin/bash

- name: "create work user"
  shell: chown -R {{ work_user }}:{{ work_user }} /home/{{ work_user }};

- name: mkdir {{ item }}
  shell: mkdir -p {{ item }};
         chown {{ work_user }}:{{ work_user }} {{ item }};
         chmod 777 {{ item }};
  with_items:
    - "{{script_dir}}"
    - "{{download_dir}}"

#remove user
#- user: name=work state=absent remove=yes

- name: "copy some config"
  copy: src={{ item }} dest=/home/{{ work_user }}/{{ item }}
        owner={{ work_user }}
        group={{ work_user }}
        mode=0744
  with_items:
    - .vimrc